# Generated by Django 5.2.3 on 2025-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
