# Generated by Django 5.2.3 on 2025-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_address_remove_address_user_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(related_name='addresses', to='users.user'),
        ),
    ]
