# Generated by Django 5.2.3 on 2025-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_country_remove_address_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.country'),
        ),
    ]
